---

- name: Install Python Modules
  become: yes
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - pip>=9.0.3
    - setuptools>=18.5
    - ndg-httpsclient
    - pyasn1
    - pyopenssl
    - urllib3

- name: Import the NodeSource GPG key into APT
  become: yes
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add NodeSource deb repository
  become: yes
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ sansible_nodejs_version }}.x {{ ansible_distribution_release }} main"
    state: present

- name: Install Node.js
  become: yes
  apt:
    name: "nodejs={{ sansible_nodejs_version }}.*"
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Symlink nodejs to node
  become: yes
  file:
    dest: /usr/sbin/node
    force: yes
    src: /usr/sbin/nodejs
    state: link

- name: Create NPM code folders for workspace user
  become: yes
  file:
    group: "{{ sansible_nodejs_workspace_user }}"
    name: "/home/{{ sansible_nodejs_workspace_user }}/.npm-global"
    owner: "{{ sansible_nodejs_workspace_user }}"
    state: directory
  when: sansible_nodejs_workspace_user

- name: Set NPM to use workspace user folders
  become: yes
  become_user: "{{ sansible_nodejs_workspace_user }}"
  command: "npm config set prefix '/home/{{ sansible_nodejs_workspace_user }}/.npm-global'"
  when: sansible_nodejs_workspace_user

- name: Add NPM folder variables to .bashrc for workspace user
  become: yes
  become_user: "{{ sansible_nodejs_workspace_user }}"
  lineinfile:
    create: yes
    dest: "/home/{{ sansible_nodejs_workspace_user }}/.bashrc"
    insertafter: EOF
    line: "export PATH=/home/{{ sansible_nodejs_workspace_user }}/.npm-global/bin:$PATH"
  when: sansible_nodejs_workspace_user

- name: Install NPMs
  become: yes
  npm:
    executable: "{{ item.executable | default('') }}"
    global: "{{ item.global | default('no' if item.path is defined else 'yes') }}"
    ignore_scripts: "{{ item.ignore_scripts | default('no') }}"
    name: "{{ item.name }}"
    path: "{{ item.path | default('') }}"
    production: "{{ item.production | default('no') }}"
    registry: "{{ item.registry | default('') }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default('') }}"
  with_items: "{{ sansible_nodejs_npms }}"
