---

- name: Install Python Modules
  become: yes
  pip:
    name: "{{ item }}"
  with_items:
    - pip>=9.0.3
    - setuptools>=18.5
    - ndg-httpsclient
    - pyasn1
    - pyopenssl
    - urllib3

- name: Import NodeSource GPG Key
  become: yes
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add NodeSource Repository
  become: yes
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ sansible_nodejs_version }}.x {{ ansible_distribution_release }} main"
    state: present

- name: Install Node.js
  become: yes
  apt:
    name: "nodejs={{ sansible_nodejs_version }}.*"
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Symlink nodejs to node
  become: yes
  file:
    dest: /usr/sbin/node
    force: yes
    src: /usr/sbin/nodejs
    state: link

- name: Create NPM Folder for Workspace User
  become: yes
  file:
    group: "{{ sansible_nodejs_workspace_user }}"
    name: "/home/{{ sansible_nodejs_workspace_user }}/.npm-global"
    owner: "{{ sansible_nodejs_workspace_user }}"
    state: directory
  when: sansible_nodejs_workspace_user is not none

- name: Set NPM Prefix for Workspace User
  become: yes
  become_user: "{{ sansible_nodejs_workspace_user }}"
  command: "npm config set prefix '/home/{{ sansible_nodejs_workspace_user }}/.npm-global'"
  register: set_prefix
  changed_when: no
  when: sansible_nodejs_workspace_user is not none

- name: Assert Workspace User Set Correctly
  assert:
    that: set_prefix.rc == 0
  when: sansible_nodejs_workspace_user is not none

- name: Add NPM PATH to Workspace User
  become: yes
  become_user: "{{ sansible_nodejs_workspace_user }}"
  lineinfile:
    create: yes
    dest: "/home/{{ sansible_nodejs_workspace_user }}/.bashrc"
    insertafter: EOF
    line: "export PATH=/home/{{ sansible_nodejs_workspace_user }}/.npm-global/bin:$PATH"
  when: sansible_nodejs_workspace_user is not none

- name: Install NPMs
  become: yes
  become_user: "{{ sansible_nodejs_workspace_user }}"
  npm:
    executable: "{{ item.executable | default(omit) }}"
    global: "{{ item.global | default(false if item.path is defined else true) }}"
    ignore_scripts: "{{ item.ignore_scripts | default(false) }}"
    name: "{{ item.name }}"
    path: "{{ item.path | default(omit) }}"
    production: "{{ item.production | default(false) }}"
    registry: "{{ item.registry | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
  with_items: "{{ sansible_nodejs_npms }}"
