---

- name: Download GPG key
  command: curl -LO https://deb.nodesource.com/gpgkey/nodesource.gpg.key
  args:
    chdir: /tmp
    creates: /tmp/nodesource.gpg.key

- name: Import the NodeSource GPG key into apt
  become: yes
  apt_key:
    file: /tmp/nodesource.gpg.key
    state: present

- name: Add NodeSource deb repository
  become: yes
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ nodejs.version }}.x {{ ansible_distribution_release }} main"
    state: present

- name: Install Node.js
  become: yes
  apt:
    name: "nodejs={{ nodejs.version }}.*"
    state: present

- name: Symlink nodejs to node
  become: yes
  file:
    dest: /usr/sbin/node
    force: yes
    src: /usr/sbin/nodejs
    state: link

- name: Create NPM code folders for workspace user
  become: yes
  file:
    group: "{{ nodejs.workspace_user }}"
    name: "/home/{{ nodejs.workspace_user }}/.npm-global"
    owner: "{{ nodejs.workspace_user }}"
    state: directory
  when: nodejs.workspace_user

- name: Set NPM to use workspace user folders
  become: yes
  become_user: "{{ nodejs.workspace_user }}"
  command: "npm config set prefix '/home/{{ nodejs.workspace_user }}/.npm-global'"
  when: nodejs.workspace_user

- name: Add NPM folder variables to .bashrc for workspace user
  become: yes
  become_user: "{{ nodejs.workspace_user }}"
  lineinfile:
    create: yes
    dest: "/home/{{ nodejs.workspace_user }}/.bashrc"
    insertafter: EOF
    line: "export PATH=/home/{{ nodejs.workspace_user }}/.npm-global/bin:$PATH"
  when: nodejs.workspace_user

- name: Install NPMs
  become: yes
  npm:
    executable: "{{ item.executable | default('') }}"
    global: "{{ item.global | default('no' if item.path is defined else 'yes') }}"
    ignore_scripts: "{{ item.ignore_scripts | default('no') }}"
    name: "{{ item.name }}"
    path: "{{ item.path | default('') }}"
    production: "{{ item.production | default('no') }}"
    registry: "{{ item.registry | default('') }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default('') }}"
  with_items: "{{ nodejs.npms }}"
