---

- name: Converge
  hosts: all

  roles:
    - role: nodejs
      sansible_nodejs_npms:
        - name: lorem-ipsum
        - name: debug
          global: no
          path: /root/.npm-local/
      sansible_nodejs_version: 4
      when: ansible_distribution_release == "trusty"

    - role: nodejs
      sansible_nodejs_npms:
        - name: lorem-ipsum
        - name: debug
          global: no
          path: /home/nodejs_test/.npm-local/
      sansible_nodejs_workspace_user: nodejs_test
      sansible_nodejs_version: 7
      when: ansible_distribution_release == "xenial"

    - role: nodejs
      sansible_nodejs_npms:
        - name: lorem-ipsum
        - name: debug
          global: no
          path: /home/nodejs_test/.npm-local/
      sansible_nodejs_workspace_user: nodejs_test
      sansible_nodejs_version: 10
      when: ansible_distribution_release == "bionic"
